### ISSUE TITLE
Ignore exceptions in non-debug mode for `default` cache

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/tecken#1111]
You can simulate that Redis connections fail with:
```
redis-cache:6379> client pause 10000
OK
```
(10 seconds).

You get this error when trying to upload a symbols .zip during this window of time:

```
eb_1          | Traceback (most recent call last):
web_1          |   File "/usr/local/lib/python3.6/site-packages/django_redis/cache.py", line 32, in _decorator
web_1          |     return method(self, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django_redis/cache.py", line 81, in get
web_1          |     client=client)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django_redis/client/default.py", line 204, in get
web_1          |     raise ConnectionInterrupted(connection=client, parent=e)
web_1          | django_redis.exceptions.ConnectionInterrupted: Redis TimeoutError: Timeout reading from socket
web_1          |
web_1          | During handling of the above exception, another exception occurred:
web_1          |
web_1          | Traceback (most recent call last):
web_1          |   File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 137, in run
web_1          |     self.result = application(self.environ, self.start_response)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 142, in __call__
web_1          |     response = self.get_response(request)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 78, in get_response
web_1          |     response = self._middleware_chain(request)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
web_1          |     response = response_for_exception(request, exc)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
web_1          |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
web_1          |     response = get_response(request)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
web_1          |     response = response or self.get_response(request)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
web_1          |     response = response_for_exception(request, exc)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
web_1          |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
web_1          |     response = get_response(request)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
web_1          |     response = response or self.get_response(request)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
web_1          |     response = response_for_exception(request, exc)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
web_1          |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
web_1          |     response = get_response(request)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
web_1          |     response = response or self.get_response(request)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
web_1          |     response = response_for_exception(request, exc)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
web_1          |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
web_1          |     response = get_response(request)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
web_1          |     response = response or self.get_response(request)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
web_1          |     response = response_for_exception(request, exc)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
web_1          |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
web_1          |     response = get_response(request)
web_1          |   File "/app/tecken/tokens/middleware.py", line 33, in __call__
web_1          |     response = self.get_response(request)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
web_1          |     response = response_for_exception(request, exc)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
web_1          |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
web_1          |     response = get_response(request)
web_1          |   File "/app/tecken/useradmin/middleware.py", line 94, in __call__
web_1          |     response = self.process_request(request)
web_1          |   File "/app/tecken/useradmin/middleware.py", line 103, in process_request
web_1          |     if cache.get(cache_key) is None:
web_1          |   File "/usr/local/lib/python3.6/site-packages/django_redis/cache.py", line 39, in _decorator
web_1          |     raise e.parent
web_1          |   File "/usr/local/lib/python3.6/site-packages/django_redis/client/default.py", line 202, in get
web_1          |     value = client.get(key)
web_1          |   File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 976, in get
web_1          |     return self.execute_command('GET', name)
web_1          |   File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 668, in execute_command
web_1          |     return self.parse_response(connection, command_name, **options)
web_1          |   File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 680, in parse_response
web_1          |     response = connection.read_response()
web_1          |   File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 624, in read_response
web_1          |     response = self._parser.read_response()
web_1          |   File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 284, in read_response
web_1          |     response = self._buffer.readline()
web_1          |   File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 216, in readline
web_1          |     self._read_from_socket()
web_1          |   File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 187, in _read_from_socket
web_1          |     raise TimeoutError("Timeout reading from socket")
web_1          | redis.exceptions.TimeoutError: Timeout reading from socket
```

With http://niwinz.github.io/django-redis/latest/#_memcached_exceptions_behavior you can make the django-redis swallow *all* errors. I've tried it and it makes uploads go through!! Obviously it's going to be behave as if the cache is `/dev/null`.

You can test this too by executing that `CLIENT PAUSE` and playing with the Django shell. It even gets the logging right!

```
# In a separate terminal with the Redis cache cli I ran: `client pause 10000`
>>> from django.core.cache import cache
>>> cache.set('foo', 'bar', 60)
INFO 2018-09-05 21:09:37,684 raven.contrib.django.client.DjangoClient Raven is not configured (logging is disabled). Please see the documentation for more information.
ERROR 2018-09-05 21:09:37,673 django_redis.cache Redis TimeoutError: Timeout reading from socket
>>> cache.get('foo')
>>>
```

If we enable this by default for the `default` CACHES configuration we should be able to allow some downtime on the Redis Cache cluster without breaking Symbol Upload.

**Comment by peterbe** [comment]
We should probably NOT ignore all exceptions when `settings.DEBUG` is True. That makes sure local devs quickly notice using the Redis cache in a way that would always fail independent of operational problems.
